"""Initial migration - 鍒涘缓8寮犺〃

Revision ID: cac671f41ffb
Revises: 
Create Date: 2025-12-31 12:10:30.938396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac671f41ffb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='日志ID'),
    sa.Column('operator_id', sa.String(length=20), nullable=False, comment='操作人ID'),
    sa.Column('action_time', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.Column('action_type', sa.String(length=20), nullable=False, comment='操作类型'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory',
    sa.Column('id', sa.Integer(), nullable=False, comment='实验室ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='实验室名称'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='实验室位置'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.String(length=10), nullable=False, comment='管理员ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='管理员姓名'),
    sa.Column('manage_scope', sa.Integer(), nullable=True, comment='管理范围（实验室ID）'),
    sa.ForeignKeyConstraint(['manage_scope'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='设备ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='设备名称'),
    sa.Column('lab_id', sa.Integer(), nullable=True, comment='所属实验室ID'),
    sa.Column('category', sa.Integer(), nullable=False, comment='设备类别 (1:学院, 2:实验室)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='设备状态 (1:正常...)'),
    sa.Column('next_avail_time', sa.DateTime(), nullable=True, comment='下次可用时间（冗余字段）'),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.String(length=10), nullable=False, comment='导师ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='导师姓名'),
    sa.Column('dept', sa.String(length=50), nullable=True, comment='所属部门'),
    sa.Column('lab_id', sa.Integer(), nullable=False, comment='所属实验室ID'),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.String(length=10), nullable=False, comment='学生ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='学生姓名'),
    sa.Column('dept', sa.String(length=50), nullable=False, comment='所属部门'),
    sa.Column('lab_id', sa.Integer(), nullable=True, comment='所属实验室ID'),
    sa.Column('t_id', sa.String(length=10), nullable=True, comment='导师ID'),
    sa.Column('lab_name', sa.String(length=50), nullable=True, comment='实验室名称（冗余字段）'),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratory.id'], ),
    sa.ForeignKeyConstraint(['t_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeslot',
    sa.Column('slot_id', sa.BigInteger(), nullable=False, comment='时间段ID'),
    sa.Column('equip_id', sa.BigInteger(), nullable=False, comment='设备ID'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='结束时间'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='是否激活 (1:激活, 0:禁用)'),
    sa.ForeignKeyConstraint(['equip_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='预约ID'),
    sa.Column('student_id', sa.String(length=10), nullable=True, comment='学生ID'),
    sa.Column('teacher_id', sa.String(length=10), nullable=True, comment='导师ID'),
    sa.Column('equip_id', sa.BigInteger(), nullable=False, comment='设备ID'),
    sa.Column('status', sa.Integer(), nullable=False, comment='预约状态 (0:待审, 1:通过...)'),
    sa.Column('apply_time', sa.DateTime(), nullable=False, comment='申请时间'),
    sa.Column('approver_id', sa.String(length=10), nullable=True, comment='审批人ID'),
    sa.Column('approve_time', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.Column('user_name', sa.String(length=50), nullable=True, comment='用户名（冗余字段）'),
    sa.Column('equip_name', sa.String(length=100), nullable=True, comment='设备名称（冗余字段）'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='价格（冗余字段）'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间（冗余字段）'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间（冗余字段）'),
    sa.CheckConstraint('(student_id IS NOT NULL AND teacher_id IS NULL) OR (student_id IS NULL AND teacher_id IS NOT NULL)', name='check_reservation_user'),
    sa.ForeignKeyConstraint(['equip_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('timeslot')
    op.drop_table('student')
    op.drop_table('teacher')
    op.drop_table('equipment')
    op.drop_table('admin')
    op.drop_table('laboratory')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
